### ISSUE TITLE
Code Dependencies

### ISSUE THREAD

**Issue by DennisSSDev** [nlebedenco/TPCE#3]
I was wondering if it's possible to use the animation warping nodes separate from the ex Character? From looking at the comments, it seems that you'd only want to use those animations hand in hand with your character bp...

**Comment by Chosker** [comment]
Im only really using the warp + footplacement nodes. Its the editor+game stuff that causes problems, not the exCharacter itself

**Comment by DennisSSDev** [comment]
I've taken a look at the nodes, and yeah you can use the indirectly from the rest of the plugin. Those nodes actually seem to be borrowed from a different UE4 plugin: https://www.unrealengine.com/marketplace/en-US/animgraphnode
